apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentuniv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: univapp
  template:
    metadata:
      labels:
        app: univapp
    spec:
      containers:
        - name: univ
          image: abirhsaini/univ
          ports:
            - containerPort: 8081
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqluniv
  template:
    metadata:
      labels:
        app: mysqluniv
    spec:
      containers:
        - name: mysql
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: univ
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-volume-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_USER
              value: root
            - name: PMA_PASSWORD
              value: root
          ports:
            - containerPort: 80