apiVersion: v1
kind: Service
metadata:
  name: serviceuniv
spec:
  selector:
    app: univapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort
