version: "3"
networks: 
  UNIV:
volumes:
  db_data:


services:
  mysql-db:
    container_name: mysql
    image: mysql:latest
    networks:
      - UNIV
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=univ
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - UNIV
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "80:80"
    depends_on:
      - mysql-db
  app-jee: 
    build:
      context: .
      dockerfile: Dockerfile
      image: nexus:8081/univ
    networks:
      - UNIV
 
    ports: 
      - "8082:8080"
    container_name: univ
    depends_on:
      - phpmyadmin
    
